ALTER TABLE "Sale"
ADD COLUMN IF NOT EXISTS "sriStatus" TEXT NOT NULL DEFAULT 'NOT_APPLICABLE',
ADD COLUMN IF NOT EXISTS "sriAccessKey" TEXT,
ADD COLUMN IF NOT EXISTS "sriXml" TEXT,
ADD COLUMN IF NOT EXISTS "sriGeneratedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "sriSentAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "sriAuthorizationNumber" TEXT,
ADD COLUMN IF NOT EXISTS "sriAuthorizationDate" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "sriError" TEXT;

ALTER TABLE "SaleLine"
ADD COLUMN IF NOT EXISTS "unit" TEXT NOT NULL DEFAULT 'Unidad',
ADD COLUMN IF NOT EXISTS "incomeTaxRetention" DECIMAL(18, 6) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "ivaRetention" DECIMAL(18, 6) NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS "Sale_tenantId_companyId_sriStatus_idx" ON "Sale"("tenantId", "companyId", "sriStatus");
CREATE INDEX IF NOT EXISTS "Sale_tenantId_sriAccessKey_idx" ON "Sale"("tenantId", "sriAccessKey");
